### PR TITLE
Builds in JDK8 & Recent versions of Jenkins

### PR DESCRIPTION
**Pull request by mdkf**
Builds against recent versions of Jenkins
Should make it easier to make it pipeline compatible

### CODE REVIEW

**Comment by kwhetstone** [comment]
This looks great.  Would love to see this get pulled in.

**Comment by emerssso** [comment]
Seconding the hope to see this change pulled in. Would love to get this plugin pipeline compatible. This is currently blocking my team from adopting pipeline for several projects.

**Comment by mdkf** [comment]
@jhansche Thank!

**Comment by lecogiteur** [comment]
Could you make a new release with last commits?

**Pull request merged**
